### ISSUE TITLE
how to use  bind function     External js  function ?

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material-jquery#6]
how to use  bind function     External js  function ?

if i want to click menu a item after do something ,but use js do this .how to write?

@Override
  public void onModuleLoad() {
    $(".myclass").css("display", "block");
    
  }

**Comment by BenDol** [comment]
Import `import static gwt.material.design.jquery.client.api.JQuery.$;`

Then you can use the API as you would in JavaScript, so see [JQuery API](http://api.jquery.com/)

**Comment by Neo110** [comment]
i meas how to in this function call js ?

  @UiHandler("autoFormat")
  void onAutoFormatClick(ClickEvent event) {

  }

**Comment by BenDol** [comment]
I already linked you to the JQuery documentation, this isn't our realm of support sorry. You will just need to do the research.

**Comment by Neo110** [comment]
fine ,Thanks
